# Generated by Django 4.1.5 on 2023-01-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_remove_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.FilePathField(
                null=True,
                path="/media/xbebex/59B8EC7E6243CB65/temp/myPortfolio/portfolio/static/portfolio/images",
            ),
        ),
    ]
